name: bikepacking
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_charts: ^22.2.12
  dart_either: ^1.0.0
  url_launcher: ^6.1.14
  go_router: ^10.1.2
  http: ^1.1.0
  shared_preferences: ^2.2.1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.0
  provider: ^6.0.5
  timezone: ^0.9.2
  flutter_polyline_points: ^2.0.0
  google_maps_flutter: ^2.5.0
  location: ^5.0.3
  street_view_platform_interface: ^1.0.8
  flutter_google_street_view:
    git:
      url: https://github.com/liorboyango/flutter_street_view.git
      path: flutter_google_street_view
      ref: master
  google_maps_webservice:
    git:
      url:  https://github.com/foxide123/google_maps_webservice.git
      ref: master
  flutter_google_places_hoc081098:
    git:
      url: https://github.com/foxide123/flutter_google_places_hoc081098.git
      ref: main
  google_api_headers: 
    git:
      url: https://github.com/foxide123/google_api_headers.git
      ref: main
  path_provider: ^2.1.1
  permission_handler: ^10.2.0
  font_awesome_flutter: ^10.5.0
  flutter_local_notifications: ^15.1.1
  flutter_map: ^5.0.0
  maplibre_gl:
    git:
      url: https://github.com/maplibre/flutter-maplibre-gl.git
      ref: main
  sensors_plus: ^4.0.0
  flutter_compass: ^0.8.0
  xml: ^6.3.0
  webview_flutter: ^4.4.1
  file_picker: ^6.1.1
  google_fonts: ^6.1.0
  geolocator: ^10.1.0
  flutter_vpn: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
