// Generated by https://quicktype.io
import 'package:equatable/equatable.dart';

class Athlete extends Equatable{
    final int? id;
    final String? username;
    final int? resourceState;
    final String? firstname;
    final String? lastname;
    final dynamic bio;
    final dynamic city;
    final dynamic state;
    final dynamic country;
    final String? sex;
    final bool? premium;
    final bool? summit;
    final String? createdAt;
    final String? updatedAt;
    final int? badgeTypeId;
    final dynamic weight;
    final String? profileMedium;
    final String? profile;
    final dynamic friend;
    final dynamic follower;

    const Athlete({
        this.id,
        this.username,
        this.resourceState,
        this.firstname,
        this.lastname,
        this.bio,
        this.city,
        this.state,
        this.country,
        this.sex,
        this.premium,
        this.summit,
        this.createdAt,
        this.updatedAt,
        this.badgeTypeId,
        this.weight,
        this.profileMedium,
        this.profile,
        this.friend,
        this.follower,
    });

    const Athlete.empty():
      this(
        id: 0,
        username: "",
        resourceState: 0,
        firstname: "",
        lastname: "",
        bio: "",
        city: "",
        state: "",
        country: "",
        sex: "",
        premium: false,
        summit: false,
        createdAt: "",
        updatedAt: "",
        badgeTypeId: 0,
        weight: "",
        profileMedium: "",
        profile: "",
        friend: "",
        follower: "",
      );

    @override
    List<Object?> get props => [];
}
