// Generated by https://quicktype.io
import 'package:bikepacking/features/strava/domain/enities/athlete.dart';

class AthleteModel extends Athlete {
  const AthleteModel({
    super.id,
    super.username,
    super.resourceState,
    super.firstname,
    super.lastname,
    super.bio,
    super.city,
    super.state,
    super.country,
    super.sex,
    super.premium,
    super.summit,
    super.createdAt,
    super.updatedAt,
    super.badgeTypeId,
    super.weight,
    super.profileMedium,
    super.profile,
    super.friend,
    super.follower,
  });

  factory AthleteModel.fromJson(Map<String, dynamic> json) {
    return AthleteModel(
      id: json['id'],
      username: json['username'],
      resourceState: (json['resource_state']).toInt(),
      firstname: json['first_name'],
      lastname: json['last_name'],
      bio: json['bio'],
      city: json['city'],
      state: json['state'],
      country: json['country'],
      sex: json['sex'],
      premium: json['premium'],
      summit: json['summit'],
      createdAt: json['created_at'],
      updatedAt: json['updated_at'],
      badgeTypeId: json['badge_type_id'],
      weight: json['weight'],
      profileMedium: json['profile_medium'],
      profile: json['profile'],
      friend: json['friend'],
      follower: json['follower'],
    );
  }
}
